#!/usr/bin/sh -eu

# xmobar source code directory
SRC="$HOME/.xmobar"

# installation directory
DST="$HOME/bin"

# cabal version
CBL="3.10.1.0"
# CBL="3.6.2.0"

# set the return code
ERR=0

# test existence of source and dst

if ! test -d "$SRC"; then
  ERR=1
  >&2 echo "ERROR: $SRC is not a valid directory"
  exit "$ERR"
fi

if ! test -d "$DST"; then
  ERR=1
  >&2 echo "ERROR: $DST is not a valid directory"
  exit "$ERR"
fi

cd "$SRC"

# install binary to $DST wtih cabal version $CBL
ghcup -c run --cabal "$CBL" -- cabal install config \
  --enable-executable-stripping \
  --enable-optimization=2 \
  --overwrite-polic=always \
  --installdir="$DST"

# exit with error code of last command
exit "$?"
