#!/usr/bin/sh -eu

# xmobar source code directory
SRC="$HOME/.xmobar"

# installation directory
DST="$HOME/bin"

# real path of installed xmobar
XMB=$(realpath "$(which xmobar)")

# ghc version
GHC="9.2.8"

# cabal version
# CBL="3.8.1.0"
CBL="3.6.2.0"

# name of cached build binary
OUT="$SRC/xmobar-$(uname -m)-linux"

# error code
ERR=0

if test "$#" -gt 1; then
  ERR=1
  >&2 echo "ERROR: too many arguments"
  exit "$ERR"
fi

if ! test -d "$SRC"; then
  ERR=1
  >&2 echo "ERROR: $SRC is not a valid directory"
  exit "$ERR"
fi

if ! test -d "$DST"; then
  ERR=1
  >&2 echo "ERROR: $DST is not a valid directory"
  exit "$ERR"
fi

if test "$#" -eq 1; then
  OUT="$1"
fi

cd "$SRC"

# if test -z "$XMB" || test "$SRC/Main.hs" -nt "$XMB"; then
ghcup -c run --ghc "$GHC" --cabal "$CBL" -- cabal install config \
  --enable-executable-stripping \
  --enable-optimization=2 \
  --overwrite-polic=always \
  --installdir="$DST"
ERR=$?
# fi

if test "$ERR" -ne 0; then
  >&2 echo "ERROR: build failure"
  exit "$ERR"
fi

ln -sf "$DST/xmobar" "$SRC/xmobar"
if test "$?" -ne 0; then
  ERR="$?"
  >&2 echo "ERROR: link failure"
  exit "$ERR"
fi

ln -sf "$SRC/xmobar" "$OUT"
if test "$?" -ne 0; then
  ERR="$?"
  >&2 echo "ERROR: link failure"
  exit "$ERR"
fi

exit "$ERR"
